### ISSUE TITLE
Remove redundant data and cloning in the cache

### ISSUE THREAD

**Issue by haraldng** [Wkkkkk/preprocessor#4]
Currently, the data stored in `LfuCache`, `LruCache`, and `Controller` are redundant, since every time we do the gets using the `IndexMap`. This means that we are also doing an unnecessary `clone()` for every `put()`.

We can therefore just keep integers to represent the data in `LfuCache`, `LruCache`, and `Controller` and only store the actual data `IndexMap` like this:

```
pub struct CacheModel {
    cache_type: CacheType,
    current_index: u32,
    lfu_cache: LfuCache<u32, PhantomData<u32>>,
    lru_cache: LruCache<u32, PhantomData<u32>>,
    lecar_cache: Controller // Fix this in LeCar,
    index_cache: IndexMap<u32, CacheKey>,
}
```

Every time we do a put, we increment `current_index`. Then we need to check what got evicted (which is what gets returned from `put()` and `insert()`) and also remove it from the `IndexMap`.

**Comment by Wkkkkk** [comment]
Yeah, we can try to optimize it this way.

**Comment by Wkkkkk** [comment]
Here are some changes I did:
Now the cache model is defined as (LRU as example):
```
pub struct LruUniCache {
    capacity: usize,
    lru_cache: LruCache<usize, PhantomData<bool>>,
    index_cache: IndexMap<T, PhantomData<bool>>,
}
```
To save an item in the cache, we first insert it into `IndexMap` and then save the index into LRU cache. If it already exists in the cache, then the key is promoted. Otherwise we check if the cache is full, if so we pop out an item. We do not remove the popped-out items from `IndexMap` because the the `remove` operation will change the order/index of other keys in the map.

To get the index of an item, we search it in `IndexMap` and LRU cache. Only if we find it in cache do we return the index.
